campgrounds:
  alta_lake:
    resource_location_id: -2147483396
    name: Alta Lake
  dash_point: 
    resource_location_id: -2147483389
    name: Dash Point
  anderson_lake:
    resource_location_id: -2147483527
    name: Anderson Lake
  griffith_priday:
    resource_location_id: -2147483535
    name: "Griffith-Priday State Park"
  battle_ground:
    resource_location_id: -2147483395
    name: "Battle Ground Lake State Park"
  bay_view:
    resource_location_id: -2147483394
    name: "Bay View State Park"
  beacon_rock:
    resource_location_id: -2147483405
    name: "Beacon Rock State Park"
  belfair: 
    resource_location_id: -2147483319
    name: "Belfair State Park"
  birch_bay:
    resource_location_id: -2147483393
    name: "Birch Bay State Park"
  bogachiel:
    resource_location_id: -2147483460
    name: "Bogachiel State Park"
  bridgeport:
    resource_location_id: -2147483392
    name: "Bridgeport State Park"
  brooks_memorial:
    resource_location_id: -2147483458
    name: "Brooks Memorial State Park"
  camano_island:
    resource_location_id: -2147483293
    name: "Camano Island State Park"
  cape_disappointment:
    resource_location_id: -2147483316
    name: "Cape Disappointment State Park"
  conconully:
    resource_location_id: -2147483391
    name: "Conconully State Park"
  illahee:
    resource_location_id: -2147483380
    name: "Illahee State Park"
  manchester:
    resource_location_id: -2147483371
    name: "Manchester State Park"
  scenic_beach:
    resource_location_id: -2147483359
    name: "Scenic Beach State Park"
  maryhill:
    resource_location_id: -2147483370
    name: "Maryhill State Park"
  fort_worden:
    resource_location_id: -2147483383
    name: "Fort Worden State Park"
  posey:
    resource_location_id: -2147483302
    name: "Posey Island Marine State Park"
  jarrell_cove:
    resource_location_id: -2147483442
    name: "Jarrell Cove State Park"
  obstruction_pass:
    resource_location_id: -2147483232
    name: "Obstruction Pass State Park"
  blake_island:
    resource_location_id: -2147483404
    name: "Blake Island State Park"
  hope_island:
    resource_location_id: -2147483230
    name: "Hope Island (Mason)"
  columbia_hills:
    resource_location_id: -2147483456
    name: "Columbia Hills State Park"